server:
  port: 8773

spring:
  application:
    name: service-sentinel
  cloud:
    sentinel:
      transport:
        port: 8773
        dashboard: localhost:8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



