server:
  port: 8773

spring:
  application:
    name: service-sentinel
  cloud:
    sentinel:
      transport:
        port: 8773
        dashboard: localhost:8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: service-sentinel  # 自定义服务名称信息
    prefer-ip-address: true #访问路径可以显示ip地址



