server:
  port: 8772
spring:
  profiles:
    active: rewritepath_route
  application:
    name: gateway-filter
---
spring:
  cloud:
    gateway:
      routes:
      - id: add_request_header_route
        uri: http://httpbin.org:80/get
        predicates:
        - After=2017-01-20T17:42:47.789-07:00[America/Denver]
        filters:
        - AddRequestHeader=X-Request-Foo, Bar
  profiles: add_request_header_route
---
spring:
  cloud:
    gateway:
      routes:
      - id: rewritepath_route
        uri: https://blog.csdn.net
        predicates:
        - Path=/sunny/**
        filters:
        - RewritePath=/sunny/(?<segment>.*), /$\{segment}
  profiles: rewritepath_route