server:
  port: 8762

spring:
  application:
    name: service-hi

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: service-hi  # 自定义服务名称信息
    prefer-ip-address: true  #访问路径可以显示ip地址
