spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sunnyday94/sunny-practice-springcloud  #配置git仓库地址
          search-paths: springcloud-config  #配置仓库路径
          username:    # 访问git仓库的用户名       Git仓库为公开仓库，可以不填写用户名和密码
          password:    # 访问git仓库的用户密码
      label: master  #配置仓库的分支

server:
  port: 8767
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
