spring:
  application:
    name: config-server
  profiles:
    active: native #native读取本地;git读取git仓库
  cloud:
    config:
      label: dev  #配置仓库的分支
      server:
        git:
          uri: https://github.com/sunnyday94/sunny-practice-springcloud  #配置git仓库地址
          search-paths: springcloud-config  #配置仓库路径
          username:    # 访问git仓库的用户名       Git仓库为公开仓库，可以不填写用户名和密码
          password:    # 访问git仓库的用户密码
        native:
          search-locations: file:///E:/IDEAWorkSpace/sunny-practice-springcloud/springcloud-config/ #配置本地仓库路径

server:
  port: 8767
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: config-server  # 自定义服务名称信息
    prefer-ip-address: true #访问路径可以显示ip地址
